using Lab2_WebAPI_v4.Data.Entities;
using Lab2_WebAPI_v4.Data.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace Lab2_WebAPI_v4.Data.Repos
{
    /// <summary>
    /// Repository responsible for database operations related to blog posts.
    /// Communicates directly with Entity Framework DbContext.
    /// </summary>
    public class PostRepo : IPostRepo
    {
        private readonly AppDbContext _context;

        /// <summary>
        /// Constructor – injects the application's DbContext.
        /// </summary>
        public PostRepo(AppDbContext context)
        {
            _context = context;
        }

        // -------------------- GET ALL POSTS --------------------

        /// <summary>
        /// Retrieves all posts from the database.
        /// </summary>
        /// <returns>List of Post entities.</returns>
        public async Task<List<Post>> GetAllPostsAsync()
        {
            return await _context.Posts.ToListAsync();
        }

        public async Task<Post?> GetByIdAsync(int postId)
        {
            return await _context.Posts
                .SingleOrDefaultAsync(p => p.PostID == postId);
        }

        // -------------------- ADD POST --------------------

        /// <summary>
        /// Adds a new post to the database.
        /// Ensures that PostID is not manually set (identity column).
        /// </summary>
        public async Task AddPostAsync(Post post)
        {
            // Identity column validation (PostID should be auto-generated by database)
            if (post.PostID != 0)
                throw new ArgumentException("PostID must be 0 when creating a new post.");

            await _context.Posts.AddAsync(post);
            await _context.SaveChangesAsync();
        }

        // -------------------- UPDATE POST --------------------

        /// <summary>
        /// Updates an existing post.
        /// Only the post owner (matching UserID) can update it.
        /// </summary>
        /// <returns>True if update succeeded, otherwise false.</returns>
        public async Task<bool> UpdatePostAsync(Post post)
        {
            // Fetch original post and verify ownership
            var postOrg = await _context.Posts
                .SingleOrDefaultAsync(p =>
                    p.PostID == post.PostID &&
                    p.UserID == post.UserID);

            if (postOrg == null)
                return false;

            // Update only allowed fields
            postOrg.Title = post.Title;
            postOrg.Text = post.Text;
            postOrg.CategoryID = post.CategoryID;

            await _context.SaveChangesAsync();
            return true;
        }

        // -------------------- DELETE POST --------------------

        /// <summary>
        /// Deletes a post.
        /// Only the post owner can delete it.
        /// </summary>
        public async Task<bool> DeletePostAsync(int postId, int userId)
        {
            // Verify that post exists and belongs to the user
            var post = await _context.Posts
                .SingleOrDefaultAsync(p =>
                    p.PostID == postId &&
                    p.UserID == userId);

            if (post == null)
                return false;

            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();

            return true;
        }

        // -------------------- SEARCH BY TITLE --------------------

        /// <summary>
        /// Searches posts by title.
        /// Performs a partial match using SQL LIKE through EF Core.
        /// </summary>

        public async Task<List<Post>> SearchByTitleAsync(string title)
        {
            /*
             Uses Contains() which translates to SQL LIKE '%title%'.
             This allows partial matching in the database.
            */

            return await _context.Posts
                .Where(p => p.Title.Contains(title))
                .ToListAsync();
        }

        // -------------------- SEARCH BY CATEGORY --------------------

        /// <summary>
        /// Retrieves posts belonging to a specific category.
        /// </summary>

        public async Task<List<Post>> SearchByCategoryAsync(int categoryId)
        {
            return await _context.Posts
                .Where(p => p.CategoryID == categoryId)
                .ToListAsync();
        }
    }
}